# Header
title: C++ Benchmarks
subtitle: "Work in progress"

# Site
# url: "https://unitatem.github.io"
# baseurl: "/cpp_benchmarks"
repository: "unitatem/cpp_benchmarks"

description: "Work in progress"

search: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single

# Author
name: "unitatem"
email: unitatem@gmail.com
github_username:  unitatem


# Build settings
include: ["_pages"]
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
